// Flat config — ESLint 9+ format. Run with `npm run lint`.
//
// Philosophy: opt-in, not opt-out. We start from the recommended baseline for
// TypeScript + React, layer in prettier integration so lint and prettier
// can't disagree, and turn OFF whole CRATES of stylistic rules that would
// either (a) fight with code that's already shipped, or (b) duplicate what
// `tsc --noEmit` already catches. The goal is catching real bugs and
// inconsistencies, not re-formatting working code.
//
// Rule categories we explicitly avoid here:
//   - formatting rules (spacing, quotes, semis) → prettier owns these
//   - "prefer X syntax" rewrites → they'd dirty every existing file
//   - rules already enforced by `tsconfig.strict` + `noUncheckedIndexedAccess`
//
// When you need to silence a specific line, prefer an inline enable/disable
// over a permanent config carve-out.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import prettierConfig from 'eslint-config-prettier';

export default tseslint.config(
  // ── Global ignores ────────────────────────────────────────────────
  // Anything that isn't first-party source we maintain.
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.vercel/**',
      '**/db/migrations/**', // generated by drizzle-kit — don't lint
      '**/*.config.{js,cjs,mjs,ts}', // vite/postcss/tailwind/drizzle configs
      '**/*.d.ts', // ambient declarations (vite-env, etc.)
    ],
  },

  // ── Base: eslint recommended + typescript-eslint recommended ──────
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // ── Project-wide defaults ─────────────────────────────────────────
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.es2022,
      },
    },
    rules: {
      // `no-unused-vars` from the JS config is too noisy on TS — TS handles
      // unused detection via `tsc` and respects `_`-prefixed params. The
      // typescript-eslint variant below (`@typescript-eslint/no-unused-vars`)
      // is what we actually want.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Allow short-circuit && and ?? for the common `foo && foo.bar` /
      // default-value patterns without forcing the operators everywhere.
      'no-unused-expressions': 'off',
      // Prefer `const` where the binding isn't reassigned — catches accidental
      // `let` prevalence, but doesn't fail on legitimate mutation.
      'prefer-const': 'warn',
      // Disallow `console.log` in source (use a logger or remove). Allowed in
      // scripts (one-offs) and tests (vitest).
      'no-console': [
        'warn',
        { allow: ['warn', 'error', 'info'] },
      ],
    },
  },

  // ── React (client) ────────────────────────────────────────────────
  {
    files: ['client/**/*.{ts,tsx}'],
    plugins: {
      react,
      'react-hooks': reactHooks,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
      },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      // We use the new JSX transform (`jsx: 'react-jsx'` in client/tsconfig.json),
      // so React doesn't need an explicit import.
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
    },
  },

  // ── Server / shared (Node) ────────────────────────────────────────
  // Already covered by the base globals: { ...globals.node }, above.
  // This block is here in case server-specific rules get added later.
  {
    files: ['server/**/*.{ts,tsx}', 'shared/**/*.{ts,tsx}', 'api/**/*.ts'],
  },

  // ── Scripts and one-offs ──────────────────────────────────────────
  // `console.*` is fine here (these are debug-y by nature), and we don't want
  // to fail on `any`-typed responses from ad-hoc API probes — they're
  // exploratory, not production code paths.
  {
    files: ['server/scripts/**/*.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  // ── Tests ─────────────────────────────────────────────────────────
  {
    files: ['**/__tests__/**/*.{ts,tsx}', '**/*.test.{ts,tsx}'],
    languageOptions: {
      globals: {
        ...globals.jest,
      },
    },
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  // ── Turn OFF all rules that conflict with Prettier ────────────────
  // This MUST be last so it can override any rule above that would
  // otherwise fight with prettier's output.
  prettierConfig,
);
